#+title: Tr14 methods
#+author: Jonathan Aguilar
#+date: 
#+startup: beamer

#+export_file_name: tr14_psf_subtraction.pdf
#+options: tex:t toc:nil author:nil H:2



* Assembling the catalog of point sources
Here's what remains:
- Finalize q-parameter cut for cluster/background separation
- Finalize master and point source catalogs and write to disk
* Performing PSF subtraction
Based heavily on cite:Strampelli_2020 
** Catalog cleaning
*** Stamp size selection
For PSF subtraction, a stamp should contain a target star and no other /known/ point sources. All stamps must be the same size. To choose the proper size, we want to optimize between two quantities:
1. increase the search region for companions
2. decrease the number of stamps with a neighbor present.
#1 has a natural limit - PSF subtraction is only useful in the regime where the background is dominated by the extended PSF of a bright star. It is irrelevant far from the star. Our experience with Orion suggests that we can achieve $\Delta\mathrm{mag} \sim 6-7$ at 0.5" separation. It is not useful to extend our stamps much beyond this region, so probably a stamp radius of 5-6 pixels would do it.

We can make a plot of the pairwise distances to see how many stars are closer to each other than this radius. We would have to eliminate all those stars, plus a few pixels of buffer to account for the PSF wings. cite:Strampelli_2020 places the cut at 1.5", or $11 \times 11$ pixels.
*** Bad pixel removal
Perform an independent search for bad pixels in the selected stamps using a 10-sigma threshold. cite:Strampelli_2020 didn't find any, so not sure what we would have done with them.
*** ACS catalog matching
cite:Strampelli_2020 matched with ACS catalog from cite:Robberto_2013 to find non-stellar objects
Do we have such a catalog available?
*** Store all the stamps on disk?
Or would it be better to pull them out of the exposures every time?
** PSF subtraction process
*** Collect the library of postage stamps
*** Select a target stamp
*** Select appropriate reference stamps
- Reference stamps must be /clean/:
  - Central source of the reference stamp must be a point source (i.e. star)
  - The central source should have small photometric uncertainty ($\sigma_{F127M} < 0.01$)
  - There must be no other (known) point sources in the stamp
- Reference stamps should be ranked according to similarity with the target stamp cite:Ruane_2019
  - mean-squared error
  - pearson correlation coefficient
  - structural similarity index metric
- Can be chosen from point sources on nearby detector positions
*** Assemble reference stamp using KLIP and subtract it from the target stamp
Parameters to tweak:
- number of references (let's see how many references are typically available first)
- number of KL modes
  cite:Strampelli_2020 choose the modes that minimize the standard deviation of the residual stamp while maximizing the brightest residual pixel
** Search for candidate companions
*** First pass
- Companion must be detected in both filters at the same separation and PA (to within 1 pixel)
- Companion must be detected in more than one set of KLIP parameters
*** Candidate photometry
**** Used for:
- cluster/background membership assignment
- mass estimation
**** Method and calibration
- 4-pixel photometry, placed in the orientation that maximizes the signal around a candidate pixel
- Calibrated using the PSF photometry in the master catalog
- Must correct for flux lost to PSF over-subtraction.
  This is measured by artificial star injection
*** False positive analysis
- Use artificial star injections to build a receiver operating characteristic for a particular bin (as a function of primary magnitude, contrast, and separation)
- cite:Strampelli_2020 required candidates to be in a regime with AUC $\ge$ 0.7
- Invert the ROC curves to get an SNR threshold that corresponds to the desired false positive rate
*** Systematic sources of false positives must also be considered
- Ghosts of bright stars in previous exposures
- Extended sources
- Contamination from nearby stars
* Steps
** Next
** Next next
** Future

* References
bibliographystyle:plain
bibliography:manuscript.bib
