#+title: Tr14 methods
#+author: Jonathan Aguilar

#+OPTIONS: tex:t

* Assembling the catalog of point sources
...later...
* Performing PSF subtraction
** Steps from cite:Strampelli_2020 
*** Catalog cleaning
**** Stamp size selection
For PSF subtraction, a stamp should contain a target star and no other /known/ point sources. All stamps must be the same size. To choose the proper size, we want to optimize between two quantities:
1. increase the search region for companions
f2. decrease the number of stamps with a neighbor present.
#1 has a natural limit - PSF subtraction is only useful in the regime where the background is dominated by the extended PSF of a bright star. It is irrelevant far from the star. Our experience with Orion suggests that we can achieve $\Delta~mag \sim 6-7$ at 0.5" separation. It is not useful to extend our stamps much beyond this region, so probably a radius of 5-6 pixels would do it.

We can make a plot of the pairwise distances to see how many stars are closer to each other than this radius. We would have to eliminate all those stars, plus a few pixels of buffer to account for the PSF wings. cite:Strampelli_2020 places the cut at 1.5".
**** Bad pixel removal
Perform an independent search for bad pixels in the selected stamps using a 10-sigma threshold. Didn't find any, so not sure what we would have done with them.
**** ACS catalog matching
Matched with ACS catalog from cite:Robberto_2013 to find non-stellar objects
*** PSF subtraction process
**** Collect the library of postage stamps
**** Select a target stamp
**** Select appropriate reference stamps
- Reference stamps must be /clean/:
  - Central source of the reference stamp must be a point source (i.e. star)
  - The central source should have small photometric uncertainty ($\sigma_f127M < 0.01$)
  - There must be no other (known) point sources in the stamp
- Reference stamps should be ranked according to similarity with the target stamp cite:Ruane_2019
  - mean-squared error
  - pearson correlation coefficient
  - structural similarity index metric
- Can be chosen from point sources on nearby detector positions
**** Assemble reference stamp using KLIP and subtract it from the target stamp
Parameters to tweak:
- number of references (let's see how many references are typically available first)
- number of KL modes
  cite:Strampelli_2020 choose the modes that minimize the standard deviation of the residual stamp while maximizing the brightest residual pixel
**** Search for companions


* Citations
bibliography:manuscript.bib
