#+TITLE: List of Tables
#+AUTHOR: Jonathan Aguilar

This document contains a list of tables for the Tr14 database, and their descriptions.
They were assembled loosely (i.e. poorly) following the procedure laid out in [[https://learning.oreilly.com/library/view/database-design-for/9780133122282/ch07.html][Database Design for Mere Mortals, Ch. 7]].

* Preliminary Table List
** Procedure
*** Identify implied subjects
Review the [[./list_of_fields.org][List of Fields]]. If you can group some into a subject, add that subject to the preliminary tables list
*** Use the List of Subjects 
Merge the list of implied subjects with the list of subjects you made [[./list_of_subjects.org][here]].
** Tables
*** stars 
formerly known as Astrophysical objects table
**** star_id
**** x_mast, y_mast
x and y position in the master frame
**** phot_i, e_phot_i
Photometry (and uncertainty) in Filter Fi, where i is a label for the filter
**** cluster_memb
Does the star belong to the cluster (True) or the background (False)
*** Point sources table
A "point source" is the detection of an astrophysical object in a particular exposure
**** ps_id                                                            :PK:
unique id for the point source.
**** star_id                                                         :FK:
the astrophysical object it corresponds to.
**** x_mast, y_mast
x and y position for that point source in the master frame.
**** x_exp, y_exp
x and y position for this particular exposure.
**** phot, e_phot
Photometry and uncertainty.
**** filter_id
The filter used for the exposure.
**** exp_id
The exposure the point source was found in.
*** Stamps table
Stamp ID and data quality
**** stamp_id
unique identifier for each stamp
**** ps_id
ID of the point source in the center of the stamp
**** star_id
ID of the astrophysical object in the center of the stamp (redundant)?
**** stamp_file
File name where the stamp is saved
**** data quality flags?
***** hot_pixels
Number of hot pixels in the stamp?
***** maybe 1 field for every data quality flag
number of pixels in the stamp that match that DQ flag
**** ref_flag
Formerly "good_ref"
Flag for if this can be used as a reference for PSF subtraction.
*** Filters table
This table keeps track of the name and ID of each filter in the observations
**** filter_id
A unique ID that can be incremented for an arbitrary number of filters
**** filter_name
HST name for a filter, e.g. "F139M"
*** Headers tables
These tables store the header information for each exposure/flt.fits file.
See documentation in the [[https://hst-docs.stsci.edu/wfc3dhb/chapter-2-wfc3-data-structure/2-2-wfc3-file-structure#id-2.2WFC3FileStructure-2.2.3ContentsofIndividualArrays][WFC3 Data Handbook]]. The fields are the header keywords, and the field values are the header keyword values
**** SCI
Science data - a.k.a. the flux-calibrated images, with counts in e/s
**** ERR
Estimate of the statistical uncertainty associated with each corresponding science image pixel
**** DQ
data quality headers. each pixel contains a bit word with data quality flags
**** SAMP
for IR data only, the number of samples used to derive the pixel values in the science image
**** TIME
for IR data only, effective integration time associated with each science image pixel
*** Data quality table
This table contains the flag value, the binary code, and a short description of the meaning
*** Candidates table
Basically same data as point sources, but for the candidates
** Future tables
   These tables don't need to be implemented until we start doing PSF subtraction
*** Companions table
    All the same info as the point sources table, but also:
**** companion_id                                                     :PK:
**** sep, pa
*** Subtraction table
    This table stores the parameters used for a PSF subtraction
**** target_id
id for the target stamp
**** reference_id_i..n
     ids for the reference stamps

* Final Table List
Options for table type: data, linking, subset, or validation
** stars
*** Type
Data
*** Description
This table contains a list of all the unique stars that are identified in the observations. 
We need this table to keep track of which star each point source corresponds to, so that we can combine point source stamps to improve detection statistics during our analysis. Ultimately, the final science products will rely on interpretation of the distribution and properties of the astrophysical objects detected during our survey.
** point_sources
*** Type
Data
*** Description
This table contains every point source detected in every exposure taken during the observations. 
The point sources are important because they are the fundamental result of each *observation* and must be collected and combined for interpretation. Multiple point source detections of the same star can be combined for improved analysis. The master list of unique astrophysical objects is derived by transforming the list of point sources onto the plane of the sky and combining overlapping point sources.
** candidaes
*** Type
Data
*** Description
This table contains the basic information for all candidates, such as the ID of the primary star, separation position angle. photometry, and the stamp(s) in which it was found.
** stamps
*** Type
Data
*** Description
This table keeps track of the data quality in each image stamp. 
The image stamps are generated by selecting a stamp of pixels around each point source in the database. This table will contain summary statistics for all the data quality flags present in each pixel contained in the stamp, for help assessing if the information contained in the stamp is reliable.
** filters
*** Type
Subset
*** Description
This table stores the names of the HST filters that correspond to the filter IDs
** headers
This set of tables contains all the header information from the exposures, except for the history and comments. These should be read-only.
*** hdr_sci
**** Type
data
**** Description
Science headers
*** hdr_err
**** Type
data
**** Description
error  headers
*** hdr_dq
**** Type
data
**** Description
data quality headers
*** hdr_samp
**** Type
data
**** Description
sampling headers
*** hdr_time
**** Type
data
**** Description
exposure time headers

* Tables and fields
** stars
| stars           |
|-----------------+
| star_id         |
| x_mast          |
| y_mast          |
| star_phot_fi    |
| star_e_phot_fi  |
| star_clust_memb |

** point_sources
| point_sources |
+---------------+
| ps_id         |
| ps_exp_id     |
| ps_filter_id  |
| ps_phot       |
| ps_e_phot     |
| ps_y_exp      |
| ps_x_exp      |

** candidates


** stamps
| stamps         |
|----------------|
| stamp_id       |
| stamp_file     |
| stamp_ref_flag |
** stamp_dq_flags
| stamp_dq_flags      |
|---------------------|
| stamp_id            |
| stamp_dq_flag       |
| stamp_dq_flag_value |
** filters
| filters   |
+-----------+
| filt_id   |
| filt_name |
** headers
| headers  |
+----------|
| hdr_sci  |
| hdr_err  |
| hdr_dq   |
| hdr_samp |
| hdr_time |
